[package]
name = "pluvialis-app"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
eframe = "0.35"
egui = "0.35"
env_logger = "0.11"
log = { workspace = true }
pluvialis-core = { version = "0.1.0", path = "../pluvialis-core" }
