//! English orthography rules, used when a suffix attaches to a word.
//!
//! GENERATED by scratchpad/gen_orthography.py from Plover's
//! `plover/system/english_stenotype.py`. Do not edit by hand: regenerate.
//!
//! **These rules are Plover's work, not this project's.** Copyright Joshua
//! Harlan Lifton and the Open Steno Project contributors, GPL-2.0-or-later, used
//! here under the "or later" clause. Only the Python to Rust regex syntax
//! conversion is ours. Recorded in `ATTRIBUTION.md`; keep that file accurate.
//!
//! Patterns match against `word + " ^ " + suffix`, so `artistic ^ ly`
//! becomes `artistically` rather than `artisticly`.

/// `(pattern, replacement)` pairs, tried in order.
pub static RULES: [(&str, &str); 38] = [
    (r"^(.*[aeiou]c) \^ ly$", r"${1}ally"),
    (r"^(.+[aeioubmnp])le \^ ly$", r"${1}ly"),
    (r"^(.*t)e \^ (ry|ary)$", r"${1}ory"),
    (r"^(.+)m \^ tor(y|ily)$", r"${1}mator${2}"),
    (r"^(.+)se \^ ar(y|ies)$", r"${1}sor${2}"),
    (r"^(.*[naeiou])te? \^ cy$", r"${1}cy"),
    (r"^(.*(?:s|sh|x|z|zh)) \^ s$", r"${1}es"),
    (
        r"^(.*(?:oa|ea|i|ee|oo|au|ou|l|n|(?<![gin]a)r|t)ch) \^ s$",
        r"${1}es",
    ),
    (r"^(.+[bcdfghjklmnpqrstvwxz])y \^ s$", r"${1}ies"),
    (r"^(.+)ie \^ ing$", r"${1}ying"),
    (r"^(.+[cdfghlmnpr])y \^ ist$", r"${1}ist"),
    (
        r"^(.+[bcdfghjklmnpqrstvwxz])y \^ ([a-hj-xz].*)$",
        r"${1}i${2}",
    ),
    (r"^(.+)te \^ en$", r"${1}tten"),
    (r"^(.+[ae]) \^ e(n|ns)$", r"${1}${2}"),
    (r"^(.+)y \^ (ial|ially)$", r"${1}${2}"),
    (
        r"^(.+i) \^ if(y|ying|ied|ies|ication|ications)$",
        r"${1}f${2}",
    ),
    (
        r"^(.*[^aeiou])y \^ if(y|ying|ied|ies|ication|ications)$",
        r"${1}if${2}",
    ),
    (r"^(.+)ic \^ (ical|ically)$", r"${1}${2}"),
    (r"^(.+)ology \^ ic(al|ally)$", r"${1}ologic${2}"),
    (r"^(.*)ry \^ ica(l|lly|lity)$", r"${1}rica${2}"),
    (r"^(.*[l]) \^ is(t|ts)$", r"${1}is${2}"),
    (r"^(.*)ry \^ ity$", r"${1}rity"),
    (r"^(.*)l \^ ity$", r"${1}lity"),
    (r"^(.+)rm \^ tiv(e|ity|ities)$", r"${1}rmativ${2}"),
    (r"^(.+)e \^ tiv(e|ity|ities)$", r"${1}ativ${2}"),
    (
        r"^(.+)y \^ iz(e|es|ing|ed|er|ers|ation|ations|able|ability)$",
        r"${1}iz${2}",
    ),
    (
        r"^(.+)y \^ is(e|es|ing|ed|er|ers|ation|ations|able|ability)$",
        r"${1}is${2}",
    ),
    (
        r"^(.+)al \^ iz(e|ed|es|ing|er|ers|ation|ations|m|ms|able|ability|abilities)$",
        r"${1}aliz${2}",
    ),
    (
        r"^(.+)al \^ is(e|ed|es|ing|er|ers|ation|ations|m|ms|able|ability|abilities)$",
        r"${1}alis${2}",
    ),
    (
        r"^(.+)ar \^ iz(e|ed|es|ing|er|ers|ation|ations|m|ms)$",
        r"${1}ariz${2}",
    ),
    (
        r"^(.+)ar \^ is(e|ed|es|ing|er|ers|ation|ations|m|ms)$",
        r"${1}aris${2}",
    ),
    (
        r"^(.*[lmnty]) \^ iz(e|es|ing|ed|er|ers|ation|ations|m|ms|able|ability|abilities)$",
        r"${1}iz${2}",
    ),
    (
        r"^(.*[lmnty]) \^ is(e|es|ing|ed|er|ers|ation|ations|m|ms|able|ability|abilities)$",
        r"${1}is${2}",
    ),
    (r"^(.+)al \^ olog(y|ist|ists|ical|ically)$", r"${1}olog${2}"),
    (r"^(.+)(ar|er|or) \^ ish$", r"${1}${2}ish"),
    (r"^(.+e)e \^ (e.+)$", r"${1}${2}"),
    (
        r"^(.+[bcdfghjklmnpqrstuvwxz])e \^ ([aeiouy].*)$",
        r"${1}${2}",
    ),
    (
        r"^(.*(?:[bcdfghjklmnprstvwxyz]|qu)[aeiou])([bcdfgklmnprtvz]) \^ ([aeiouy].*)$",
        r"${1}${2}${2}${3}",
    ),
];

/// Suffixes that are tried under another spelling as well.
pub static ALIASES: [(&str, &str); 2] = [("able", "ible"), ("ability", "ibility")];
