"""Generate the Rust orthography rule table from Plover's source.

Transcribing 33 regexes by hand is exactly the kind of task that produces a
silent off-by-one in a character class, so we read them from the original.
"""

import ast
import re
from pathlib import Path

SRC = Path(r"F:\Steno\plover\plover\system\english_stenotype.py")
OUT = Path(r"F:\Steno\Pluvialis\crates\pluvialis-core\src\orthography_rules.rs")

src = SRC.read_text(encoding="utf-8")

start = src.index("ORTHOGRAPHY_RULES = [")
start = src.index("[", start)
end = src.index("ORTHOGRAPHY_RULES_ALIASES")
segment = src[start:end].rstrip().rstrip(",")
# Trim back to the closing bracket of the list literal.
segment = segment[: segment.rindex("]") + 1]
rules = ast.literal_eval(segment)

astart = src.index("ORTHOGRAPHY_RULES_ALIASES = {")
astart = src.index("{", astart)
aend = src.index("}", astart) + 1
aliases = ast.literal_eval(src[astart:aend])


def to_rust_replacement(rep: str) -> str:
    """Python uses \\1 for group references, Rust uses ${1}.

    The braces are not optional here: `$1ally` would be read as a group named
    "1ally" rather than group 1 followed by text.
    """
    return re.sub(r"\\(\d+)", r"${\1}", rep)


def rust_raw(s: str) -> str:
    # Our patterns contain backslashes and no quotes, so a raw string works.
    assert '"' not in s, s
    return f'r"{s}"'


lines = [
    "//! English orthography rules, used when a suffix attaches to a word.",
    "//!",
    "//! GENERATED by scratchpad/gen_orthography.py from Plover's",
    "//! `plover/system/english_stenotype.py`. Do not edit by hand: regenerate.",
    "//!",
    "//! Patterns match against `word + \" ^ \" + suffix`, so `artistic ^ ly`",
    "//! becomes `artistically` rather than `artisticly`.",
    "",
    "/// `(pattern, replacement)` pairs, tried in order.",
    f"pub static RULES: [(&str, &str); {len(rules)}] = [",
]
for pattern, replacement in rules:
    lines.append(f"    ({rust_raw(pattern)}, {rust_raw(to_rust_replacement(replacement))}),")
lines.append("];")
lines.append("")
lines.append("/// Suffixes that are tried under another spelling as well.")
lines.append(f"pub static ALIASES: [(&str, &str); {len(aliases)}] = [")
for k, v in aliases.items():
    lines.append(f'    ("{k}", "{v}"),')
lines.append("];")
lines.append("")

OUT.write_text("\n".join(lines), encoding="utf-8")
print(f"wrote {OUT}")
print(f"  {len(rules)} rules, {len(aliases)} aliases")
