"""Build the Pluvialis app icon from the plover illustration.

`crates/pluvialis-app/assets/icon-source.png` was generated by the author with
ChatGPT, so no third party holds copyright in it and it ships under the
project's own licence. See ATTRIBUTION.md.

Run this after changing the source art, then rebuild, because `build.rs` embeds
`icon.ico` into the executable:

    py -X utf8 tools/make_icon.py
    cargo build --release

## The white page has to go, and the corners with it

The illustration sits on a white page with a rounded square inside it. The
corner is a squircle, not a circular arc, so the transparent area is found by
flood filling the white in from the four corners rather than by guessing the
curve. That is exact by construction and it cannot clip the artwork. White
*inside* the bird is untouched, however pale, because the fill can only reach
what connects to the outside.

## Do not crop in

An earlier version zoomed in for the small sizes, on the theory that a tighter
crop survives being shrunk. It does not work on this artwork and it shipped a
visible bug: the bird already fills 74% of the frame across and 82% down,
leaving 8 to 9 percent margin, so a zoom of 1.2 or more runs the bill off the
right edge and the tail off the left. The taskbar draws 24 and 32 pixel icons,
which is exactly where the cropping showed, and the icon looked cut off on
every side.

So every size uses the artist's framing unchanged. Softness at 16 and 24 pixels
is dealt with by sharpening after the resize, which costs no margin.
"""

import struct
from io import BytesIO
from pathlib import Path

from PIL import Image, ImageDraw, ImageFilter

SOURCE = Path(__file__).resolve().parents[1] / "crates" / "pluvialis-app" / "assets" / "icon-source.png"
ASSETS = SOURCE.parent

# The rounded square inside the white page, found by walking in from each edge
# until the pixel stopped being white.
BOX = (66, 52, 1188, 1199)

# White is the page, not the artwork. The bird's belly is #FDF4E6, far enough
# from #FFFFFF that this tolerance cannot eat into it.
WHITE_TOLERANCE = 10
SENTINEL = (255, 0, 255)

SIZES = (256, 128, 64, 48, 32, 24, 16)

# Below this, downsampling softens the bird's outline and the bill starts to
# disappear. Sharpening buys back the definition a crop was supposed to.
SHARPEN_AT_OR_BELOW = 48


def transparent_outside(image: Image.Image) -> Image.Image:
    """Make everything outside the rounded square transparent."""
    probe = image.convert("RGB")
    for corner in (
        (0, 0),
        (probe.width - 1, 0),
        (0, probe.height - 1),
        (probe.width - 1, probe.height - 1),
    ):
        ImageDraw.floodfill(probe, corner, SENTINEL, thresh=WHITE_TOLERANCE)

    flat = probe.load()
    mask = Image.new("L", image.size, 255)
    edit = mask.load()
    for y in range(image.height):
        for x in range(image.width):
            if flat[x, y] == SENTINEL:
                edit[x, y] = 0
    # The fill stops at the first pixel outside the tolerance, so the edge it
    # leaves is hard. A sub-pixel blur puts the antialiasing back, and these
    # corners are the outline of the whole icon.
    mask = mask.filter(ImageFilter.GaussianBlur(0.6))

    out = image.convert("RGBA")
    out.putalpha(mask)
    return out


def scaled(art: Image.Image, size: int) -> Image.Image:
    """One icon size, sharpened at the small end.

    The sharpen is applied to the colour channels only. Running it over the
    alpha would put a bright halo around the rounded corners, which is the one
    place the icon is silhouetted against whatever is behind it.
    """
    small = art.resize((size, size), Image.LANCZOS)
    if size > SHARPEN_AT_OR_BELOW:
        return small

    alpha = small.getchannel("A")
    rgb = small.convert("RGB").filter(
        ImageFilter.UnsharpMask(radius=0.8, percent=70, threshold=0)
    )
    out = rgb.convert("RGBA")
    out.putalpha(alpha)
    return out


def write_ico(images: dict[int, Image.Image], path: Path) -> None:
    """Assemble an ICO holding every size.

    Written here rather than with Pillow's ICO writer so the per size images
    are stored exactly as produced above, sharpening included, instead of being
    resized again from one source.

    Each entry is stored as PNG, which every Windows since Vista reads, and
    which keeps the alpha channel without the AND mask a BMP entry needs.
    """
    sizes = sorted(images, reverse=True)
    payloads = []
    for size in sizes:
        buffer = BytesIO()
        images[size].save(buffer, format="PNG", optimize=True)
        payloads.append(buffer.getvalue())

    offset = 6 + 16 * len(sizes)
    header = struct.pack("<HHH", 0, 1, len(sizes))
    entries = b""
    for size, payload in zip(sizes, payloads):
        entries += struct.pack(
            "<BBBBHHII",
            0 if size == 256 else size,  # 0 means 256 in this format
            0 if size == 256 else size,
            0,  # not a palette
            0,  # reserved
            1,  # colour planes
            32,  # bits per pixel
            len(payload),
            offset,
        )
        offset += len(payload)

    path.write_bytes(header + entries + b"".join(payloads))


def main() -> None:
    art = transparent_outside(Image.open(SOURCE).convert("RGBA").crop(BOX))
    # Rendered once at high resolution, so every size is a clean reduction of
    # the same picture rather than a reduction of a reduction.
    art = art.resize((1024, 1024), Image.LANCZOS)

    per_size = {size: scaled(art, size) for size in SIZES}

    # eframe's runtime window icon: the title bar and alt-tab.
    per_size[256].save(ASSETS / "icon.png")
    # Embedded into the exe by build.rs: the taskbar and Explorer icon.
    write_ico(per_size, ASSETS / "icon.ico")

    print("icon.png", (ASSETS / "icon.png").stat().st_size, "bytes")
    print("icon.ico", (ASSETS / "icon.ico").stat().st_size, "bytes,",
          len(per_size), "sizes:", ", ".join(str(s) for s in SIZES))


if __name__ == "__main__":
    main()
