"""Build the Pluvialis app icon from the plover illustration and install it.

`pluvialis.png` was generated by the user with ChatGPT, so no third party holds
copyright in it and it ships with the project under the same licence. Recorded
in ATTRIBUTION.md.

Two things the naive "resize to every size" approach gets wrong, and this does
not:

**The corners.** The illustration sits on a white page with a rounded square
inside it. The corner is a squircle, not a circular arc, so the transparent
area is found by flood filling the white in from the four corners rather than
by guessing the curve. Exact by construction, and it cannot clip the artwork.

**Optical scaling.** One image resized to 16 pixels turns to mush: the legs
become a grey smear and the head is lost. So the icon is drawn at three crops
and each size takes the one that suits it, zooming in as the icon gets smaller.
Windows only ever draws one size at a time, so the change is never visible as
an inconsistency, and the small sizes stay legible. That needs an ICO holding a
different image per size, which Pillow cannot write, so the container is
assembled here.
"""

import struct
from io import BytesIO
from pathlib import Path

from PIL import Image, ImageDraw, ImageFilter

SOURCE = Path(__file__).resolve().parents[1] / "crates" / "pluvialis-app" / "assets" / "icon-source.png"
ASSETS = SOURCE.parent

# The rounded square inside the white page, found by walking in from each edge
# until the pixel stopped being white.
BOX = (66, 52, 1188, 1199)

# White is the page, not the artwork. The bird's belly is #FDF4E6, far enough
# from #FFFFFF that this tolerance cannot eat into it.
WHITE_TOLERANCE = 10
SENTINEL = (255, 0, 255)

# The original squircle's corner radius, as a fraction of the side. Needed to
# put the corners back after a crop.
CORNER = 0.196

# Which crop each size uses. Smaller icon, tighter crop.
#   0.84  the whole bird including the legs
#   0.70  a little closer, legs still suggested
#   0.58  head and body only, which is all that survives at 16 pixels
PLAN = {256: 0.84, 128: 0.84, 64: 0.70, 48: 0.70, 32: 0.70, 24: 0.58, 16: 0.58}

# Where each crop is taken from. The bird sits low and right of centre, so the
# empty sky comes off the top rather than an even slice off every side.
ANCHOR = {0.84: (0.62, 0.82), 0.70: (0.60, 0.55), 0.58: (0.60, 0.34)}


def transparent_outside(image: Image.Image) -> Image.Image:
    """Make everything outside the rounded square transparent."""
    probe = image.convert("RGB")
    for corner in (
        (0, 0),
        (probe.width - 1, 0),
        (0, probe.height - 1),
        (probe.width - 1, probe.height - 1),
    ):
        ImageDraw.floodfill(probe, corner, SENTINEL, thresh=WHITE_TOLERANCE)

    flat = probe.load()
    mask = Image.new("L", image.size, 255)
    edit = mask.load()
    for y in range(image.height):
        for x in range(image.width):
            if flat[x, y] == SENTINEL:
                edit[x, y] = 0
    # The fill stops at the first pixel outside the tolerance, so the edge it
    # leaves is hard. A sub-pixel blur puts the antialiasing back, and these
    # corners are the outline of the whole icon.
    mask = mask.filter(ImageFilter.GaussianBlur(0.6))

    out = image.convert("RGBA")
    out.putalpha(mask)
    return out


def round_corners(image: Image.Image) -> Image.Image:
    """Re-round the corners after a crop has cut them off."""
    radius = int(min(image.size) * CORNER)
    # Drawn at four times the size and shrunk, because `rounded_rectangle`
    # itself does not antialias.
    mask = Image.new("L", (image.width * 4, image.height * 4), 0)
    ImageDraw.Draw(mask).rounded_rectangle(
        (0, 0, mask.width - 1, mask.height - 1), radius=radius * 4, fill=255
    )
    mask = mask.resize(image.size, Image.LANCZOS)

    out = image.copy()
    out.putalpha(
        Image.composite(out.getchannel("A"), Image.new("L", image.size, 0), mask)
    )
    return out


def crops(art: Image.Image) -> dict[float, Image.Image]:
    """One high resolution image per crop level."""
    w, h = art.size
    made = {}
    for zoom, (fx, fy) in ANCHOR.items():
        keep_w, keep_h = int(w * zoom), int(h * zoom)
        left, top = int((w - keep_w) * fx), int((h - keep_h) * fy)
        cropped = art.crop((left, top, left + keep_w, top + keep_h))
        made[zoom] = round_corners(cropped).resize((1024, 1024), Image.LANCZOS)
    return made


def write_ico(images: dict[int, Image.Image], path: Path) -> None:
    """Assemble an ICO holding a different image per size.

    Each entry is stored as PNG, which every Windows since Vista reads, and
    which keeps the alpha channel without the AND mask a BMP entry needs.
    """
    sizes = sorted(images, reverse=True)
    payloads = []
    for size in sizes:
        buffer = BytesIO()
        images[size].save(buffer, format="PNG", optimize=True)
        payloads.append(buffer.getvalue())

    # ICONDIR, then one 16 byte ICONDIRENTRY per image, then the images.
    offset = 6 + 16 * len(sizes)
    header = struct.pack("<HHH", 0, 1, len(sizes))
    entries = b""
    for size, payload in zip(sizes, payloads):
        entries += struct.pack(
            "<BBBBHHII",
            0 if size == 256 else size,  # 0 means 256 in this format
            0 if size == 256 else size,
            0,  # not a palette
            0,  # reserved
            1,  # colour planes
            32,  # bits per pixel
            len(payload),
            offset,
        )
        offset += len(payload)

    path.write_bytes(header + entries + b"".join(payloads))


if __name__ == "__main__":
    art = transparent_outside(Image.open(SOURCE).convert("RGBA").crop(BOX))
    by_zoom = crops(art)

    per_size = {
        size: by_zoom[zoom].resize((size, size), Image.LANCZOS)
        for size, zoom in PLAN.items()
    }

    # eframe's runtime window icon. One size, so it takes the widest crop.
    per_size[256].save(ASSETS / "icon.png")
    # Embedded into the exe by build.rs: the taskbar and Explorer icon.
    write_ico(per_size, ASSETS / "icon.ico")

    print("icon.png ", (ASSETS / "icon.png").stat().st_size, "bytes")
    print("icon.ico ", (ASSETS / "icon.ico").stat().st_size, "bytes",
          "with", len(per_size), "sizes")
